stages:
  - test
  - deploy_test
  - deploy_production

cache:
  paths:
    - node_modules/


# 测试
测试:
  stage: test
  only:
    - master
    - tags
  script:
    - echo 'test'

# 部署测试服务器
部署测试环境:
  stage: deploy_test
  only:
    - master
  tags:
    - test
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install
    - npm run build-test
    - rm -rf /usr/local/nginx/html/*
    - cp -r dist/* /usr/local/nginx/html/


# 部署生产服务器
部署生产环境服务器 1:
  stage: deploy_production
  only:
    - tags
  tags:
    - production1
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install
    - npm run build
    - rm -rf /usr/share/nginx/html/*
    - cp -r dist/* /usr/share/nginx/html/

部署生产环境服务器 2:
  stage: deploy_production
  only:
    - tags
  tags:
    - production2
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install
    - npm run build
    - rm -rf /usr/share/nginx/html/*
    - cp -r dist/* /usr/share/nginx/html/
